Refactorings, Optimizations, and Formatting
db0/AI-Horde-Worker pull request #97
Opened 2023-03-12 01:34 UTC by Arborym

- A number of refactorings, comprehensions, etc.
- Apply Black formatting to files that weren't affected before it was made into a GitHub Workflow
- Apply consistent isort to files that didn't already have it

2023-03-12 04:21 UTC, AlRlC commented
Looks good, will test on my worker to validate

2023-03-12 08:20 UTC, AlRlC commented
All good on my end

2023-03-12 11:02 UTC, db0 commented
This doesn't seem to use our style. Did you use our own presets, or your own?

2023-03-12 16:08 UTC, Arborym commented
@db0 Fixed

2023-03-13 07:50 UTC, db0 commented
Can you please fix the linting errors?

2023-03-13 08:13 UTC, db0 requested changes
Thanks for the effort. Two main points

1) You should avoid removing comments, especially when they explain the `why` and not the `what`
2) A lot of stylechanges are more pythonian and/or single-line, but they have the potential to make the code more difficult to understand. It's better to be more verbose if it makes the code easier to follow. This is especially true for complex conditionals where it's better to break them into escape sequences. It's OK for now, but please keep this in mind for the future.

Please check my individual comments.

2023-03-13 08:13 UTC, db0 commented on worker/workers/framework.py
> -        while len(self.running_jobs) < self.bridge_data.max_threads:
You can leave that in for now but for readability, try to avoid adding too many conditionals. It's easier to understand with multiple if/break cases

2023-03-13 08:13 UTC, db0 commented on worker/workers/stable_diffusion.py
> -        # Sometimes a dynamic model is wwaiting in the queue,
Please avoid removing explanatory comments like these.

2023-03-13 11:35 UTC, Arborym commented on worker/bridge_data/framework.py
> +                except OSError:
Both `FileExistsError` and `PermissionError` are children of `OSError`, as seen here. Essentially, it is redundant to list those two exception types along with `OSError`.

![image](https://user-images.githubusercontent.com/105245560/224690537-c4c66bfc-0ecf-4ec4-a2bf-8af6c4508f43.png)

2023-03-13 12:21 UTC, Arborym commented
I don't know why it automatically removed the review request from the other two when I selected "Re-request Review." Sorry about that

2023-03-13 22:24 UTC, db0 commented
LGTM otherwise. @ResidentChief and @jug-dev lemme know if you have any issues, otherwise I can merge

2023-03-13 22:24 UTC, db0 approved these changes

2023-03-14 13:27 UTC, db0 commented
No response. Ok once you fix the latest conflict, I'll merge

2023-03-14 14:03 UTC, Arborym commented
@db0 All set

2023-03-14 14:28 UTC, db0 commented
Something is wrong in your merge. The csam.py version in this commit is older that the main branch

2023-03-14 15:20 UTC, Arborym commented
Just copied csam.py from origin/HEAD and refactored on that as well

2023-03-14 15:59 UTC, Arborym commented
@db0 sorry this PR was such a mess—I'm not the best with GIT

2023-03-15 09:07 UTC, merged